# Generated by Django 5.1.7 on 2025-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessorio', models.ManyToManyField(related_name='acessorios', to='core.acessorio')),
            ],
        ),
    ]
